 #content of pytest.ini :to store default command-line arguments
 #pytest configuration
 #"Whenever pytest runs, automatically apply these command-line options
[pytest]

addopts =
#-v: Verbose execution:tests/login_pagetest.py::TestLoginPage::test_get_login_page_title PASSED
#instead of just -
    -v
    --html=reports/report.html
    --alluredir=reports/allure-results
#Pytest only searches inside:tests/
testpaths = tests
#Pytest recognizes:class TestLoginPage:
python_classes = Test*
python_files = *_test.py
python_functions = test_*
markers=api:API Testcases
        ui:UI Testcases
        smoke:Smoke testcases
        regression:Regression testcases