#application/environment data: Application Configuration File
[application]
ui_url= https://eventhub.rahulshettyacademy.com/login
api_base_url=https://api.eventhub.rahulshettyacademy.com
username= test123today@gmail.com
password= Test@1234

[browser Info]
browser = chromium
headless = false
screenshot = Off
tracing = Off

